In [2]:
import torch
x = torch.zeros([2,3])

In [3]:
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x =torch.ones([2, 3, 2])
print(x)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])


In [7]:
x = torch.Tensor([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [10]:
x.size()

torch.Size([3, 4])

In [11]:
x[:, 1]

tensor([ 2.,  6., 10.])

In [13]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

print(a)


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [14]:
 a % b
    

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [18]:
mask = x > 3

In [19]:
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [24]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = X[X > limit].sum()
print(X[X > limit])
print(larger_than_limit_sum)

3
tensor([4, 5, 6, 7, 8, 9])
tensor(39)


In [25]:
y = x.clone()
y[0,0] = 99
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[99.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [26]:
x.dtype

torch.float32

In [27]:
import numpy as np
x = np.array([[1,2,3,4],
             [5,6,7,8]])
x


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [29]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [35]:
x = torch.rand([2000,3000])
x

tensor([[0.8677, 0.2243, 0.6423,  ..., 0.7659, 0.9102, 0.9371],
        [0.1845, 0.8235, 0.9904,  ..., 0.1269, 0.9750, 0.5544],
        [0.3007, 0.9505, 0.3957,  ..., 0.9797, 0.9360, 0.4685],
        ...,
        [0.4069, 0.8775, 0.9655,  ..., 0.0465, 0.8699, 0.4270],
        [0.8107, 0.1379, 0.2155,  ..., 0.8001, 0.5297, 0.7301],
        [0.5965, 0.9195, 0.8533,  ..., 0.8645, 0.8428, 0.3058]])

In [31]:
torch.cuda.is_available()

/home/byka/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370128159/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


False

In [36]:
torch.device('cpu')

device(type='cpu')

In [37]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cpu')

In [38]:
%time x = (x - x + x * 10.0) ** 2

CPU times: user 23.3 ms, sys: 31.2 ms, total: 54.5 ms
Wall time: 28.4 ms


In [5]:
x = torch.tensor(
    [[ 1.,  2.,  3.,  4.],
     [ 5.,  6.,  7.,  8.],
     [ 9., 10., 11., 12.]], requires_grad=True)

device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
x = x.to(device)

function = 10 * (x ** 2).sum()

function.backward()

print(x.grad, '<- gradient')

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]]) <- gradient


/home/byka/anaconda3/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /opt/conda/conda-bld/pytorch_1607370128159/work/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [6]:
x.grad

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]])

In [7]:
x.data -= 0.001 * x.grad

In [ ]:
x.grad.zero_()